version: '3.9'

services:
  quart_app:
    build: .
    container_name: Python_container
    ports:
      - "1234:1234"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
    restart: always
